services:
  - type: cron
    name: aiven-databricks-sync
    runtime: python
    plan: starter
    schedule: "0 */4 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python synchronizer.py
    envVars:
      - key: DB_CORE_HOST
        sync: false
      - key: DB_CORE_PORT
        sync: false
      - key: DB_CORE_USER
        sync: false
      - key: DB_CORE_PASS
        sync: false
      - key: DB_CORE_NAME
        sync: false
      - key: DATABRICKS_HOST
        sync: false
      - key: DATABRICKS_HTTP_PATH
        sync: false
      - key: DATABRICKS_TOKEN
        sync: false
      - key: DATABRICKS_CATALOG
        sync: false
      - key: DATABRICKS_SCHEMA
        sync: false
